apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - deployment-tls.yaml
  - deployment-http2.yaml
  - service.yaml
  - servicemonitor.yaml
  # Uncomment to use TLS secret from this file:
  # - secret-tls.yaml

namespace: chaos-testing

commonLabels:
  project: chaos-generator

images:
  - name: your-registry/target-http
    newName: your-registry/target-http
    newTag: latest
