/*
 * contract Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"mallekoppie/ChaosGenerator/internal/agent"
)

// getEnv retrieves an environment variable or returns a default value
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func GetConfig() ChaosAgentConfig {
	// Read from environment variables with local development defaults
	configuration := ChaosAgentConfig{
		Port:          getEnv("CHAOS_AGENT_PORT", "9001"),
		MetricsPort:   getEnv("CHAOS_AGENT_METRICS_PORT", "9091"),
		MasterAddress: getEnv("CHAOS_MASTER_ADDRESS", "localhost:9002"),
		Version:       getEnv("CHAOS_AGENT_VERSION", "2.0.0"),
	}

	log.Printf("Configuration loaded:")
	log.Printf("  Port: %s", configuration.Port)
	log.Printf("  Metrics Port: %s", configuration.MetricsPort)
	log.Printf("  Master Address: %s", configuration.MasterAddress)
	log.Printf("  Version: %s", configuration.Version)

	return configuration
}

func main() {
	config := GetConfig()

	log.Println("Chaos Agent starting...")
	log.Printf("Master address: %s", config.MasterAddress)

	// Register with master and get agent ID
	agentId, err := agent.RegisterWithMaster(config.MasterAddress, config.Port, config.MetricsPort, config.Version)
	if err != nil {
		log.Printf("Failed to register with master: %v", err)
		return
	}

	log.Printf("Registered with master. Agent ID: %s", agentId)

	// Create agent client
	client := agent.NewClient(config.MasterAddress, agentId)

	// Create context that can be cancelled
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Connect to master and start listening for commands
	if err := client.Connect(ctx); err != nil {
		log.Printf("Failed to connect to master: %v", err)
		return
	}
	defer client.Close()

	log.Println("Agent connected and listening for commands...")

	// Wait for interrupt signal
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)
	<-sigChan

	log.Println("Shutting down agent...")
	cancel()
}
