/*
 * contract Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"mallekoppie/ChaosGenerator/internal/agent"
)

// getEnv retrieves an environment variable or returns a default value
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func GetConfig() ChaosAgentConfig {
	// Read from environment variables with local development defaults
	configuration := ChaosAgentConfig{
		Port:          getEnv("CHAOS_AGENT_PORT", "9001"),
		MetricsPort:   getEnv("CHAOS_AGENT_METRICS_PORT", "9091"),
		MasterAddress: getEnv("CHAOS_MASTER_ADDRESS", "localhost:9002"),
		Version:       getEnv("CHAOS_AGENT_VERSION", "2.0.0"),
	}

	log.Printf("Configuration loaded:")
	log.Printf("  Port: %s", configuration.Port)
	log.Printf("  Metrics Port: %s", configuration.MetricsPort)
	log.Printf("  Master Address: %s", configuration.MasterAddress)
	log.Printf("  Version: %s", configuration.Version)

	return configuration
}

func main() {
	config := GetConfig()

	log.Println("Chaos Agent starting...")
	log.Printf("Master address: %s", config.MasterAddress)

	// Create context that can be cancelled
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Start metrics server
	if err := agent.StartMetricsServer(ctx, config.MetricsPort); err != nil {
		log.Printf("Failed to start metrics server: %v", err)
		return
	}

	// Wait for interrupt signal to shut down cleanly
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-sigChan
		log.Println("Shutting down agent...")
		cancel()
	}()

	// Register and connect, reconnecting automatically if the stream drops.
	agent.Run(ctx, config.MasterAddress, config.Port, config.MetricsPort, config.Version)

	log.Println("Agent stopped")
}
