// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package contracts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChaosTargetClient is the client API for ChaosTarget service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChaosTargetClient interface {
	// UC1: Health Check - Minimal overhead operation
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// UC2: Status - Lightweight JSON serialization
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// UC3: Simple Query - Standard read operation
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// UC4: Create Resource - Write operation with validation
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// UC5: List Collection - Pagination and filtering
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// UC6: Bulk Update - Batch processing
	BulkUpdate(ctx context.Context, in *BulkUpdateRequest, opts ...grpc.CallOption) (*BulkUpdateResponse, error)
	// UC7: Report Generation - CPU-intensive operation
	GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*GenerateReportResponse, error)
	// UC8: File Upload - Large request payload
	UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error)
	// UC9: Data Export - Large response payload with streaming
	ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (ChaosTarget_ExportDataClient, error)
	// UC10: Network Saturation - Extreme payload sizes
	ProcessData(ctx context.Context, in *ProcessDataRequest, opts ...grpc.CallOption) (*ProcessDataResponse, error)
	// UC11: Stream Analytics - Memory pressure testing
	StreamAnalytics(ctx context.Context, in *StreamAnalyticsRequest, opts ...grpc.CallOption) (*StreamAnalyticsResponse, error)
}

type chaosTargetClient struct {
	cc grpc.ClientConnInterface
}

func NewChaosTargetClient(cc grpc.ClientConnInterface) ChaosTargetClient {
	return &chaosTargetClient{cc}
}

func (c *chaosTargetClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) BulkUpdate(ctx context.Context, in *BulkUpdateRequest, opts ...grpc.CallOption) (*BulkUpdateResponse, error) {
	out := new(BulkUpdateResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/BulkUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) GenerateReport(ctx context.Context, in *GenerateReportRequest, opts ...grpc.CallOption) (*GenerateReportResponse, error) {
	out := new(GenerateReportResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/GenerateReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error) {
	out := new(UploadDocumentResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/UploadDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (ChaosTarget_ExportDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChaosTarget_ServiceDesc.Streams[0], "/contracts.ChaosTarget/ExportData", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaosTargetExportDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChaosTarget_ExportDataClient interface {
	Recv() (*ExportDataResponse, error)
	grpc.ClientStream
}

type chaosTargetExportDataClient struct {
	grpc.ClientStream
}

func (x *chaosTargetExportDataClient) Recv() (*ExportDataResponse, error) {
	m := new(ExportDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chaosTargetClient) ProcessData(ctx context.Context, in *ProcessDataRequest, opts ...grpc.CallOption) (*ProcessDataResponse, error) {
	out := new(ProcessDataResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/ProcessData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosTargetClient) StreamAnalytics(ctx context.Context, in *StreamAnalyticsRequest, opts ...grpc.CallOption) (*StreamAnalyticsResponse, error) {
	out := new(StreamAnalyticsResponse)
	err := c.cc.Invoke(ctx, "/contracts.ChaosTarget/StreamAnalytics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaosTargetServer is the server API for ChaosTarget service.
// All implementations must embed UnimplementedChaosTargetServer
// for forward compatibility
type ChaosTargetServer interface {
	// UC1: Health Check - Minimal overhead operation
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// UC2: Status - Lightweight JSON serialization
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// UC3: Simple Query - Standard read operation
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// UC4: Create Resource - Write operation with validation
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// UC5: List Collection - Pagination and filtering
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// UC6: Bulk Update - Batch processing
	BulkUpdate(context.Context, *BulkUpdateRequest) (*BulkUpdateResponse, error)
	// UC7: Report Generation - CPU-intensive operation
	GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error)
	// UC8: File Upload - Large request payload
	UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error)
	// UC9: Data Export - Large response payload with streaming
	ExportData(*ExportDataRequest, ChaosTarget_ExportDataServer) error
	// UC10: Network Saturation - Extreme payload sizes
	ProcessData(context.Context, *ProcessDataRequest) (*ProcessDataResponse, error)
	// UC11: Stream Analytics - Memory pressure testing
	StreamAnalytics(context.Context, *StreamAnalyticsRequest) (*StreamAnalyticsResponse, error)
	mustEmbedUnimplementedChaosTargetServer()
}

// UnimplementedChaosTargetServer must be embedded to have forward compatible implementations.
type UnimplementedChaosTargetServer struct {
}

func (UnimplementedChaosTargetServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedChaosTargetServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedChaosTargetServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedChaosTargetServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedChaosTargetServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedChaosTargetServer) BulkUpdate(context.Context, *BulkUpdateRequest) (*BulkUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkUpdate not implemented")
}
func (UnimplementedChaosTargetServer) GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedChaosTargetServer) UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedChaosTargetServer) ExportData(*ExportDataRequest, ChaosTarget_ExportDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ExportData not implemented")
}
func (UnimplementedChaosTargetServer) ProcessData(context.Context, *ProcessDataRequest) (*ProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessData not implemented")
}
func (UnimplementedChaosTargetServer) StreamAnalytics(context.Context, *StreamAnalyticsRequest) (*StreamAnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamAnalytics not implemented")
}
func (UnimplementedChaosTargetServer) mustEmbedUnimplementedChaosTargetServer() {}

// UnsafeChaosTargetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChaosTargetServer will
// result in compilation errors.
type UnsafeChaosTargetServer interface {
	mustEmbedUnimplementedChaosTargetServer()
}

func RegisterChaosTargetServer(s grpc.ServiceRegistrar, srv ChaosTargetServer) {
	s.RegisterService(&ChaosTarget_ServiceDesc, srv)
}

func _ChaosTarget_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_BulkUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).BulkUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/BulkUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).BulkUpdate(ctx, req.(*BulkUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/GenerateReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).GenerateReport(ctx, req.(*GenerateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_UploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).UploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/UploadDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).UploadDocument(ctx, req.(*UploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_ExportData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChaosTargetServer).ExportData(m, &chaosTargetExportDataServer{stream})
}

type ChaosTarget_ExportDataServer interface {
	Send(*ExportDataResponse) error
	grpc.ServerStream
}

type chaosTargetExportDataServer struct {
	grpc.ServerStream
}

func (x *chaosTargetExportDataServer) Send(m *ExportDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChaosTarget_ProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).ProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/ProcessData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).ProcessData(ctx, req.(*ProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosTarget_StreamAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosTargetServer).StreamAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.ChaosTarget/StreamAnalytics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosTargetServer).StreamAnalytics(ctx, req.(*StreamAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChaosTarget_ServiceDesc is the grpc.ServiceDesc for ChaosTarget service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChaosTarget_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contracts.ChaosTarget",
	HandlerType: (*ChaosTargetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ChaosTarget_HealthCheck_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ChaosTarget_GetStatus_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _ChaosTarget_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _ChaosTarget_CreateUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _ChaosTarget_ListUsers_Handler,
		},
		{
			MethodName: "BulkUpdate",
			Handler:    _ChaosTarget_BulkUpdate_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _ChaosTarget_GenerateReport_Handler,
		},
		{
			MethodName: "UploadDocument",
			Handler:    _ChaosTarget_UploadDocument_Handler,
		},
		{
			MethodName: "ProcessData",
			Handler:    _ChaosTarget_ProcessData_Handler,
		},
		{
			MethodName: "StreamAnalytics",
			Handler:    _ChaosTarget_StreamAnalytics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportData",
			Handler:       _ChaosTarget_ExportData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/contracts/target.proto",
}
